routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/', 'HomeController@index');
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/episode/{seriesId}/{id}', 'EpisodesController@Single')->name('SingleEpisode');
Route::get('/like/{id}', 'EpisodesController@LikeEpisode')->name('LikeEpisode');

Route::get('/series/{id}', 'SeriesController@Single')->name('SingleSeries');
Route::get('/follow/{id}', 'SeriesController@FollowSeries')->name('FollowSeries');


route::get('/search','HomeController@search')->name('search');

Route::prefix('admin')->group(function () {
    Route::get('/dashboard/', 'admin\DashboardController@index')->name('adminPanel');
    Route::resource('users', 'admin\UsersController');
    Route::resource('series', 'admin\SeriesController');
    Route::resource('episodes', 'admin\EpisodesController');
});

app/Http/Controllers/SeriesController.php
<?php

namespace App\Http\Controllers;

use App\episodes;
use App\series;
use App\UserFollowSeries;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class SeriesController extends Controller
{
    public function Single($id)
    {
        $Series = series::find($id);
        $Follows=UserFollowSeries::SeriesFollow($id);
       $SeriesEpisodes=episodes::SeriesEpisodes($id);
        return view('single_series', compact('Series','Follows','SeriesEpisodes'));
    }

    public function FollowSeries($id)
    {
        $user_id = Auth::user()->id;
        UserFollowSeries::addFollow($user_id, $id);
        return redirect()->back();
    }

}

app/Http/Controllers/admin/SeriesController.php
<?php

namespace App\Http\Controllers\admin;

use App\series;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Redirect;

class SeriesController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    protected function validateSeries()
    {
        return $this->validate(Request(),[
            'title' => 'required|max:255',
            'description' => 'required|max:1000',
            'AiringTime' => 'required|max:150',
            'StartDay'=>'required',
            'EndDay'=>'required'
        ]);
    }

    public function index()
    {
        $series = series::all();
        return view('admin.series.series-list',compact(['series']));
    }

    public function create()
    {
        return view('admin.series.series-create');
    }

    public function store(request $request)
    {
        $this->validateSeries();
        series::storeSeries($request->all());
        return Redirect::route('series.index')->with('success_alert','Series was added successfully');
    }

    public function edit($seriesID)
    {
        $series = series::find($seriesID);

        return view('admin.series.series-edit',compact(['series']));
    }

    public function update(request $request,$seriesID)
    {
        $this->validateSeries();
        series::editSeries($request,$seriesID);
        return Redirect::route('series.index')->with('warning_alert','Series was updated successfully');
    }

    public function show($seriesID)
    {
        $series = series::find($seriesID);
        return view('admin.series.series-details',compact(['series']));
    }

    public function destroy($seriesID)
    {
        series::deleteSeries($seriesID);
        return Redirect::route('series.index')->with('danger_alert','Series was deleted successfully');
    }
}

resources/views/admin/series/series-create.blade.php
@extends('admin.layouts.app')
@section('content')
    <div class="content-wrapper">

            <div class="panel panel-default">
                <div class="panel-header"><h2 class="col-xs-12">Create series</h2></div>
                <div class="panel-body">


                    <div class="row">
                        <div class="col-lg-6">
                            <form method="POST" action="{{route('series.store')}}" >
                               @csrf


                                        <div class="form-group">
                                           <label> Title</label>
                                            <input class="form-control" type="text" name="title" value="{{old('title')}}">
                                            @if ($errors->has('title'))
                                                <span >
                                                    <strong>{{ $errors->first('image') }}</strong>
                                                </span>
                                            @endif
                                        </div>
                                        <div class="form-group">
                                            <label>Description</label>
                                            <textarea class="form-control" name="description" >{{old('description')}}</textarea>
                                            @if ($errors->has('description'))
                                                <span>
                                                    <strong>{{ $errors->first('description') }}</strong>
                                                </span>
                                            @endif
                                        </div>

                                        <div class="form-group">
                                          <label>  Airing time</label>
                                            <input class="form-control" type="time" name="AiringTime" value="{{old('AiringTime')}}">
                                            @if ($errors->has('AiringTime'))
                                                <span >
                                                    <strong>{{ $errors->first('AiringTime') }}</strong>
                                                </span>
                                            @endif
                                        </div>
                                <div class="form-group">
                                    <label>Start Day</label>
                                    <input class="form-control" type="date" name="StartDay" value="{{old('StartDay')}}">
                                    @if ($errors->has('StartDay'))
                                        <span >
                                                    <strong>{{ $errors->first('StartDay') }}</strong>
                                                </span>
                                    @endif
                                </div>
                                <div class="form-group">
                                    <label>End Day</label>
                                    <input class="form-control" type="date" name="EndDay" value="{{old('EndDay')}}">
                                    @if ($errors->has('EndDay'))
                                        <span >
                                                    <strong>{{ $errors->first('EndDay') }}</strong>
                                                </span>
                                    @endif
                                </div>

                                <div>
                                    <button type="submit" class="btn btn-default">Store</button>
                                </div>
                            </form>
                        </div>

                    </div>
                    <!-- /.row (nested) -->
                </div>
                <!-- /.panel-body -->
            </div>

    </div>
@endsection

resources/views/admin/series/series-details.blade.php
@extends('admin.layouts.app')
@section('content')
    <div class="content-wrapper">

            <div class="panel panel-default">
                <div class="panel-header"><h2 class="col-xs-12">View series</h2></div>
                <div class="panel-body">


                    <div class="row">
                        <div class="col-lg-6">
                            <form >


                                <div class="form-group">
                                    Title
                                    <input disabled class="form-control" type="text" value=" {{$series->title}}">

                                </div>
                                <div class="form-group">
                                    Description
                                    <textarea disabled class="form-control" > {{$series->description}}</textarea>
                                </div>

                                <div class="form-group">
                                    Airing time
                                    <input disabled class="form-control" type="text" value="{{$series->AiringTime}}">
                                </div>
                                <div class="form-group">
                                    Start Day
                                    <input disabled class="form-control" type="text" value="{{date('l',strtotime($series->StartDay))}}">
                                </div>
                                <div class="form-group">
                                    End Day
                                    <input disabled class="form-control" type="text" value="{{date('l',strtotime($series->EndDay))}}">
                                </div>
                            </form>
                        </div>

                    </div>
                    <!-- /.row (nested) -->
                </div>
                <!-- /.panel-body -->
            </div>

    </div>

    @endsection

resources/views/admin/series/series-edit.blade.php
@extends('admin.layouts.app')
@section('content')
    <div class="content-wrapper">

            <div class="panel panel-default">
                <div class="panel-header"><h2>Edit series</h2></div>
                <div class="panel-body">


                    <div class="row">
                        <div class="col-lg-6">
                            <form method="POST" action="{{route('series.update',$series->seriesID)}}" >
                                @csrf
                                @method('PUT')


                                <div class="form-group">
                                    Title
                                    <input class="form-control" type="text" name="title" value="@if(old('title')){{old('title')}}@else{{$series->title}}@endif">
                                    @if ($errors->has('title'))
                                        <span >
                                                    <strong>{{ $errors->first('title') }}</strong>
                                                </span>
                                    @endif
                                </div>
                                <div class="form-group">
                                    Description
                                    <textarea class="form-control" name="description" >@if(old('description')){{old('description')}}@else{{$series->description}}@endif</textarea>
                                    @if ($errors->has('description'))
                                        <span >
                                                    <strong>{{ $errors->first('description') }}</strong>
                                                </span>
                                    @endif
                                </div>

                                <div class="form-group">
                                    <label>  Airing time</label>
                                    <input class="form-control" type="time" name="AiringTime" value="@if(old('AiringTime')){{old('AiringTime')}}@else{{$series->AiringTime}}@endif">
                                    @if ($errors->has('AiringTime'))
                                        <span >
                                                    <strong>{{ $errors->first('AiringTime') }}</strong>
                                                </span>
                                    @endif
                                </div>
                                <div class="form-group">
                                    <label>Start Day</label>
                                    <input class="form-control" type="date" name="StartDay" value="@if(old('StartDay')){{old('StartDay')}}@else{{$series->StartDay}}@endif">
                                    @if ($errors->has('StartDay'))
                                        <span >
                                                    <strong>{{ $errors->first('StartDay') }}</strong>
                                                </span>
                                    @endif
                                </div>
                                <div class="form-group">
                                    <label>End Day</label>
                                    <input class="form-control" type="date" name="EndDay" value="@if(old('EndDay')){{old('EndDay')}}@else{{$series->EndDay}}@endif">
                                    @if ($errors->has('EndDay'))
                                        <span >
                                                    <strong>{{ $errors->first('EndDay') }}</strong>
                                                </span>
                                    @endif
                                </div>

                                <div>
                                    <button type="submit" class="btn btn-default">Update</button>
                                </div>
                            </form>
                        </div>

                    </div>
                    <!-- /.row (nested) -->
                </div>
                <!-- /.panel-body -->
            </div>

    </div>
@endsection

resources/views/admin/series/series-list.blade.php
@extends('admin.layouts.app')
@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Series List
            </h1>
            <ol class="breadcrumb">
                <li><a href="{{route('adminPanel')}}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
                <li><a class="active" href="/admin/series">Series</a></li>

            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <div class="box">
                        <!-- /.box-header -->
                        <div class="box-body">
                            <table id="example2" class="table table-bordered table-hover">
                                <thead>
                                <tr>
                                    <th>Series Id</th>
                                    <th>Title</th>
                                    <th>Airing Time</th>
                                    <th>Start Day</th>
                                    <th>End Day</th>
                                    <th>Control</th>
                                </tr>
                                </thead>
                                <tbody>

                                @foreach ($series as $item)

                                    <tr>
                                        <td>{{$item->seriesID}}</td>
                                        <td>{{$item->title}}</td>
                                        <td>{{$item->AiringTime}}</td>
                                        <td>{{$item->StartDay}}</td>
                                        <td>{{$item->EndDay}}</td>
                                        <td>
                                            <a  href="{{route('series.edit',$item->seriesID)}}" >Edit | </a>
                                            <a href="{{route('series.show',$item->seriesID)}}" >View</a>
                                            <form method="POST" action="{{route('series.destroy',$item->seriesID)}}">
                                                @csrf
                                                @method('DELETE')
                                                <button onclick="return confirm('Are you sure?')"  >Delete</button>
                                            </form>
                                        </td>
                                    </tr>

                                @endforeach

                                </tbody>
                            </table>
                        </div>
                        <!-- /.box-body -->
                    </div>

                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>
@endsection