routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/', 'HomeController@index');
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/episode/{seriesId}/{id}', 'EpisodesController@Single')->name('SingleEpisode');
Route::get('/like/{id}', 'EpisodesController@LikeEpisode')->name('LikeEpisode');

Route::get('/series/{id}', 'SeriesController@Single')->name('SingleSeries');
Route::get('/follow/{id}', 'SeriesController@FollowSeries')->name('FollowSeries');


route::get('/search','HomeController@search')->name('search');

Route::prefix('admin')->group(function () {
    Route::get('/dashboard/', 'admin\DashboardController@index')->name('adminPanel');
    Route::resource('users', 'admin\UsersController');
    Route::resource('series', 'admin\SeriesController');
    Route::resource('episodes', 'admin\EpisodesController');
});

app/episodes.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Request;

class episodes extends Model
{
    protected $table = 'episodes';
    protected $fillable = ['title', 'description', 'thumbnail', 'video', 'series_seriesID', 'AiringTime', 'duration'];
    protected $primaryKey = 'episodeID';


    public static function storeEpisode($request)
    {
        $episode = new episodes;
        $episode->title = $request['title'];
        $episode->description = $request['description'];
        $episode->thumbnail = User::storeFiles('thumbnail');
        $episode->AiringTime = $request['AiringTime'];
        $episode->duration = $request['duration'];
        $episode->video = $request['video'];
        $episode->series_seriesID = $request['series_seriesID'];
        $episode->save();
    }

    public static function editEpisode($request, $episodeID)
    {
        $episode = episodes::find($episodeID);
        $episode->title = $request['title'];
        $episode->description = $request['description'];
        $episode->AiringTime = $request['AiringTime'];
        $episode->duration = $request['duration'];
        if (request()->hasFile('thumbnail'))
            $episode->thumbnail = User::storeFiles('thumbnail');

        if (request()->has('video'))
            $episode->video = $request['video'];
        $episode->series_seriesID = $request['series_seriesID'];
        $episode->save();
    }

    public static function deleteEpisode($episodeID)
    {
        $episode = episodes::find($episodeID);
        if ($episode != null)
            $episode->delete();
    }


    public static function getSeriesEpisodes($seriesID)
    {
        $series = series::find($seriesID);

        return [
            'series' => $series,
            'episodes' => $series->episodes->paginate(35),
            'isSeriesFollowed' => usersFollowsSeries::seriesIsFollowed($seriesID)
        ];

    }

    public static function searchForEpisodes($request)
    {
        $episode = episodes::where('title', $request['search'])->first();
        if ($episode != null)
            return true;
        else
            return false;
    }

    public static function getLatest()
    {
        $episodes = episodes::orderBy('created_at', 'desc')
            ->get();
        return $episodes;
    }

    public static function NextEpisodes($id, $episodeId)
    {
        $episodes = episodes::where("series_seriesID", $id)
            ->where("episodeID", '!=', $episodeId)
            ->get();
        return $episodes;
    }

    public function Series()
    {

        return $this->belongsTo('App\series');
    }

    public static function SeriesEpisodes($seriesID)
    {
        $episodes = episodes::where("series_seriesID", $seriesID)
            ->get();
        return $episodes;
    }

}

app/Http/Controllers/EpisodesController.php
<?php

namespace App\Http\Controllers;

use App\episodes;
use App\UserLikeEpisode;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class EpisodesController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function Single($seriesId,$id)
    {
        $Episode = episodes::where('episodeID',$id)->where('series_seriesID',$seriesId)->first();
        $Likes=UserLikeEpisode::EpisodeLikes($id);
        $NextEpisodes=episodes::NextEpisodes($Episode->Series->seriesID,$id);
        return view('single_episode', compact('Episode','Likes','NextEpisodes'));
    }

    public function LikeEpisode($id)
    {
        $user_id = Auth::user()->id;
         UserLikeEpisode::addLike($user_id,$id);

        return redirect()->back();
    }
}

app/Http/Controllers/admin/EpisodesController.php
<?php

namespace App\Http\Controllers\admin;

use App\episodes;
use App\series;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Redirect;

class EpisodesController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    protected function validateEpisodes()
    {
        return $this->validate(Request(),[
            'title' => 'required|max:255',
            'description' => 'required|max:1000',
            'series_seriesID' => 'required|numeric',
            'video' => 'required',
        ]);
    }
    public function index()
    {
        $episodes = episodes::all();

        return view('admin.episodes.episode-list',compact(['episodes']));
    }

    public function create()
    {
        $series = series::all();

        return view('admin.episodes.episode-create',compact(['series']));
    }
    public function store(request $request)
    {
        $this->validateEpisodes();

        episodes::storeEpisode($request->all());

        return Redirect::route('episodes.index')->with('success_alert','Episode was added successfully');
    }

    public function edit($episodeID)
    {
        $series = series::all();
        $episode = episodes::find($episodeID);

        return view('admin.episodes.episode-edit',compact(['series','episode']));
    }
    public function update(request $request, $episodeID)
    {
        $this->validateEpisodes();

        episodes::editEpisode($request->all(),$episodeID);

        return Redirect::route('episodes.index')->with('warning_alert','Series was updated successfully');
    }

    public function show($episodeID)
    {
        $episode = episodes::find($episodeID);

        return view('admin.episodes.episode-details',compact(['episode']));
    }

    public function delete($episodeID)
    {
        episodes::deleteEpisode($episodeID);
        return Redirect::route('episodes.index')->with('danger_alert','Series was deleted successfully');
    }

}

resources/views/admin/episodes/episode-create.blade.php
@extends('admin.layouts.app')
@section('content')
    <div class="content-wrapper">

            <div class="panel panel-default">
                <div class="panel-header"><h2 class="col-xs-12">Create Episode</h2></div>
                <div class="panel-body">


                    <div class="row">
                        <div class="col-lg-6">
                            <form method="POST" action="{{route('episodes.store')}}" enctype="multipart/form-data" >
                                @csrf


                                <div class="form-group">
                                    Title
                                    <input class="form-control" type="text" name="title" value="{{old('title')}}">
                                    @if ($errors->has('title'))
                                        <span>
                                            <strong>{{ $errors->first('image') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div class="form-group">
                                    Description
                                    <textarea class="form-control" name="description" >{{old('description')}}</textarea>
                                    @if ($errors->has('description'))
                                        <span>
                                            <strong>{{ $errors->first('description') }}</strong>
                                        </span>
                                    @endif
                                </div>

                                <div class="form-group">
                                    Episode series
                                    <select class="form-control" name="series_seriesID" >
                                        <option disabled value="">Please select series</option>
                                        @foreach($series AS $item)
                                            <option @if(old('series_seriesID') == $item->seriesID) {{"SELECTED"}} @endif value="{{$item->seriesID}}">{{$item->title}}</option>
                                         @endforeach
                                    </select>
                                    @if ($errors->has('series_seriesID'))
                                        <span>
                                            <strong>{{ $errors->first('series_seriesID') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div class="form-group">
                                    <label>  Airing time</label>
                                    <input class="form-control" type="datetime-local" name="AiringTime" value="{{old('AiringTime')}}">
                                    @if ($errors->has('AiringTime'))
                                        <span >
                                                    <strong>{{ $errors->first('AiringTime') }}</strong>
                                                </span>
                                    @endif
                                </div>
                                <div class="form-group">
                                    <label>  Duration</label>
                                    <input class="form-control" type="time" name="duration" value="{{old('duration')}}">
                                    @if ($errors->has('duration'))
                                        <span >
                                                    <strong>{{ $errors->first('duration') }}</strong>
                                                </span>
                                    @endif
                                </div>
                                <div class="form-group">
                                    Thumbnail
                                    <input class="form-control" type="file" name="thumbnail" value="{{old('thumbnail')}}">
                                    @if ($errors->has('thumbnail'))
                                        <span >
                                            <strong>{{ $errors->first('thumbnail') }}</strong>
                                        </span>
                                    @endif
                                </div>


                                <div class="form-group">
                                    Video
                                    <input class="form-control" type="text" name="video" value="{{old('video')}}">
                                    @if ($errors->has('video'))
                                        <span>
                                            <strong>{{ $errors->first('video') }}</strong>
                                        </span>
                                    @endif
                                </div>

                                <div>
                                    <button type="submit" class="btn btn-default">Store</button>
                                </div>
                            </form>
                        </div>

                    </div>
                    <!-- /.row (nested) -->
                </div>
                <!-- /.panel-body -->
            </div>

    </div>
@endsection

resources/views/admin/episodes/episode-details.blade.php
@extends('admin.layouts.app')
@section('content')

        <div class="content-wrapper">
            <div class="panel panel-default">
                <div class="panel-header"><h2 class="col-xs-12">View Episode</h2></div>
                <div class="panel-body">


                    <div class="row">
                        <div class="col-lg-6">
                            <form >


                                <div class="form-group">
                                    Title
                                    <input disabled class="form-control" type="text" value=" {{$episode->title}}">

                                </div>
                                <div class="form-group">
                                    Series Title
                                    <input disabled class="form-control" type="text" value=" {{$episode->Series->title}}">

                                </div>
                                <div class="form-group">
                                    Airing Time
                                    <input disabled class="form-control" type="text" value=" {{$episode->AiringTime}}">

                                </div>
                                <div class="form-group">
                                    Duration
                                    <input disabled class="form-control" type="text" value=" {{$episode->duration}}">

                                </div>
                                <div class="form-group">
                                    Description
                                    <textarea disabled class="form-control" > {{$episode->description}}</textarea>
                                </div>

                                <div class="form-group">
                                    <img class="img-circle" src="/{{$episode->thumbnail}}" width="100" height="100">
                                </div>
                                <iframe width="200" height="200"
                                        src="@if(old('video')){{old('video')}}@else{{str_replace('watch?v=','embed/',$episode->video)}}@endif">
                                </iframe>

                            </form>
                        </div>

                    </div>
                    <!-- /.row (nested) -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->

        </div>


@endsection

resources/views/admin/episodes/episode-edit.blade.php
@extends('admin.layouts.app')
@section('content')

        <div class="content-wrapper">
            <div class="panel panel-default">
                <div class="panel-header"><h2 class="col-xs-12">Edit Episode</h2></div>
                <div class="panel-body">


                    <div class="row">
                        <div class="col-lg-6">
                            <form method="POST" action="{{route('episodes.update',$episode->episodeID)}}" enctype="multipart/form-data" >
                                @csrf
                                @method('PUT')


                                <div class="form-group">
                                    Title
                                    <input class="form-control" type="text" name="title" value="@if(old('title')){{old('title')}}@else{{$episode->title}}@endif">
                                    @if ($errors->has('title'))
                                        <span >
                                            <strong>{{ $errors->first('title') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div class="form-group">
                                    Description
                                    <textarea class="form-control" name="description" >@if(old('description')){{old('description')}}@else{{$episode->description}}@endif</textarea>
                                    @if ($errors->has('description'))
                                        <span >
                                            <strong>{{ $errors->first('description') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div class="form-group">
                                    Episode series
                                    <select class="form-control" name="series_seriesID" >
                                        <option disabled value="">Please select series</option>
                                        @foreach($series AS $item)
                                            <option @if($episode->series_seriesID == $item->seriesID) {{"SELECTED"}} @endif value="{{$item->seriesID}}">{{$item->title}}</option>
                                        @endforeach
                                    </select>
                                    @if ($errors->has('series_seriesID'))
                                        <span>
                                            <strong>{{ $errors->first('series_seriesID') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div class="form-group">
                                    <label>  Airing time</label>
                                    <input class="form-control" type="datetime-local" name="AiringTime" value="@if(old('AiringTime')){{old('AiringTime')}}@else{{$episode->AiringTime}}@endif">
                                    @if ($errors->has('AiringTime'))
                                        <span >
                                                    <strong>{{ $errors->first('AiringTime') }}</strong>
                                                </span>
                                    @endif
                                </div>
                                <div class="form-group">
                                    <label>  Duration</label>
                                    <input class="form-control" type="time" name="duration" value="@if(old('duration')){{old('duration')}}@else{{$episode->duration}}@endif">
                                    @if ($errors->has('duration'))
                                        <span >
                                                    <strong>{{ $errors->first('duration') }}</strong>
                                                </span>
                                    @endif
                                </div>
                                <div class="form-group">
                                    Thumbnail

                                        <input class="form-control" type="file" name="thumbnail" value="@if(old('thumbnail')){{old('thumbnail')}}@else{{$episode->thumbnail}}@endif">

                                        <img  class="img-circle" width="50px" height="50px" src="/@if(old('thumbnail')){{old('thumbnail')}}@else{{$episode->thumbnail}}@endif">

                                    @if ($errors->has('thumbnail'))
                                        <span >
                                            <strong>{{ $errors->first('thumbnail') }}</strong>
                                        </span>
                                    @endif
                                </div>


                                <div class="form-group">
                                    Video
                                    <input class="form-control" type="text" name="video" value="@if(old('video')){{old('video')}}@else{{$episode->video}}@endif">
                                    <iframe width="200" height="200"
                                            src="@if(old('video')){{old('video')}}@else{{str_replace('watch?v=','embed/',$episode->video)}}@endif">
                                    </iframe>


                                @if ($errors->has('video'))
                                        <span>
                                            <strong>{{ $errors->first('video') }}</strong>
                                        </span>
                                    @endif
                                </div>

                                <div>
                                    <button type="submit" class="btn btn-default">Update</button>
                                </div>
                            </form>
                        </div>

                    </div>
                    <!-- /.row (nested) -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->

        </div>
  
@endsection

resources/views/admin/episodes/episode-list.blade.php
@extends('admin.layouts.app')
@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Episodes List
            </h1>
            <ol class="breadcrumb">
                <li><a href="{{route('adminPanel')}}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
                <li><a class="active" href="/admin/episodes">Episodes</a></li>

            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <div class="box">
                        <!-- /.box-header -->
                        <div class="box-body">
                            <table id="example2" class="table table-bordered table-hover">
                                <thead>
                                <tr>
                                    <th>Episode Id</th>
                                    <th>Thumbnail</th>
                                    <th>Title</th>
                                    <th>Airing Time</th>
                                    <th>Duration</th>
                                    <th>Series Title</th>
                                    <th>Control</th>
                                </tr>
                                </thead>
                                <tbody>

                                @foreach ($episodes as $item)

                                    <tr>
                                        <td>{{$item->episodeID}}</td>
                                        <td><img  class="img-circle" width="50px" height="50px"src="../{{$item->thumbnail}}"></td>

                                        <td>{{$item->title}}</td>
                                        <td>{{$item->AiringTime}}</td>
                                        <td>{{$item->duration}}</td>
                                        <td>{{$item->Series->title}}</td>
                                        <td>
                                            <a  href="{{route('episodes.edit',$item->episodeID)}}" >Edit | </a>
                                            <a href="{{route('episodes.show',$item->episodeID)}}" >View</a>
                                            <form method="POST" action="{{route('episodes.destroy',$item->episodeID)}}">
                                                @csrf
                                                @method('DELETE')
                                                <button onclick="return confirm('Are you sure?')"  >Delete</button>
                                            </form>
                                        </td>
                                    </tr>

                                @endforeach

                                </tbody>
                            </table>
                        </div>
                        <!-- /.box-body -->
                    </div>

                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>
@endsection